//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA_ENVIO_KAPITI
    {
        public int consecutivo { get; set; }
        public int operacion { get; set; }
        public System.DateTime fecha_envio { get; set; }
        public Nullable<System.DateTime> fecha_validado { get; set; }
        public string archivo { get; set; }
        public Nullable<byte> no_journal { get; set; }
        public Nullable<byte> no_journal_contrapartida { get; set; }
    }
}
