//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA_ERRORES_MAPEO
    {
        public int consecutivo { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public decimal error_numero { get; set; }
        public string error_descripcion { get; set; }
        public string archivo_destino { get; set; }
        public string tipo_error { get; set; }
    }
}
