//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA_IE_TRANSACCIONES
    {
        public int ID_TRANSACCION { get; set; }
        public string NOM_TRANSACCION { get; set; }
        public Nullable<System.DateTime> FEC_HOR_ULT_ENVIO { get; set; }
        public Nullable<System.DateTime> FEC_HOR_PROX_ENVIO { get; set; }
        public Nullable<System.DateTime> FECHA_TRAN { get; set; }
    
        public virtual NOM_TRANSACCIONES NOM_TRANSACCIONES { get; set; }
    }
}
