//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODIGO_OPERACION_EQ
    {
        public byte agencia { get; set; }
        public string sufijo_kapiti { get; set; }
        public string kapiti_CTP { get; set; }
        public string kapiti_C2 { get; set; }
        public string kapiti_C1 { get; set; }
        public string kapiti_P3 { get; set; }
        public string kapiti_P5 { get; set; }
    }
}
