//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCION_ENVIO
    {
        public byte agencia { get; set; }
        public string cuenta_cliente { get; set; }
        public string direccion_cliente { get; set; }
        public string cp_cliente { get; set; }
        public string colonia_cliente { get; set; }
        public Nullable<short> ubicacion { get; set; }
        public string calle_envio { get; set; }
        public string no_ext_envio { get; set; }
        public string no_int_envio { get; set; }
        public string componente_envio { get; set; }
        public string del_o_municipio_envio { get; set; }
    }
}
