//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOLD
    {
        public int producto_contratado { get; set; }
        public System.DateTime fecha_equation { get; set; }
        public short hold1 { get; set; }
        public string descripcion1 { get; set; }
        public string descripcion2 { get; set; }
        public string descripcion3 { get; set; }
        public string descripcion4 { get; set; }
        public string usuario_equation { get; set; }
        public Nullable<int> secuencia_hold { get; set; }
    
        public virtual PRODUCTO_CONTRATADO PRODUCTO_CONTRATADO1 { get; set; }
    }
}
