//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISOS_HEXA
    {
        public short permiso { get; set; }
        public short aplicacion { get; set; }
        public string nombre_permiso { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string descripcion { get; set; }
    }
}
