//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE_SWIFT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REPORTE_SWIFT()
        {
            this.OPERACION_SWIFT = new HashSet<OPERACION_SWIFT>();
        }
    
        public int no_rep_swift { get; set; }
        public System.DateTime fecha_reporte { get; set; }
        public byte agencia { get; set; }
        public short no_reporte_dia { get; set; }
        public byte tipo_reporte_swift { get; set; }
        public short no_registros { get; set; }
        public byte status_reporte { get; set; }
        public bool reenvio { get; set; }
        public bool ultimo_reporte { get; set; }
        public Nullable<short> usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPERACION_SWIFT> OPERACION_SWIFT { get; set; }
        public virtual TIPO_REPORTE_SWIFT TIPO_REPORTE_SWIFT1 { get; set; }
    }
}
