//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE_SWIFT_MT103
    {
        public int operacion { get; set; }
        public string basic_header { get; set; }
        public string app_header { get; set; }
        public string campo_20 { get; set; }
        public string campo_23 { get; set; }
        public string campo_32_date { get; set; }
        public string campo_32_ammount { get; set; }
        public string campo_50 { get; set; }
        public string campo_53 { get; set; }
        public string campo_56_aba { get; set; }
        public string campo_56_cve { get; set; }
        public string campo_57_1 { get; set; }
        public string campo_57_2 { get; set; }
        public string campo_57_3 { get; set; }
        public string campo_57_4 { get; set; }
        public string campo_57_5 { get; set; }
        public string campo_59_1 { get; set; }
        public string campo_59_2 { get; set; }
        public string campo_59_3 { get; set; }
        public string campo_59_4 { get; set; }
        public string campo_59_5 { get; set; }
        public string campo_70_1 { get; set; }
        public string campo_70_2 { get; set; }
        public string campo_70_3 { get; set; }
        public string campo_70_4 { get; set; }
        public string campo_70_5 { get; set; }
        public string campo_71 { get; set; }
        public string campo_72_1 { get; set; }
        public string campo_72_2 { get; set; }
        public string campo_72_3 { get; set; }
        public string campo_72_4 { get; set; }
        public bool status_envio { get; set; }
        public Nullable<System.DateTime> fecha_reporte { get; set; }
        public byte msg_xml { get; set; }
    
        public virtual OPERACION OPERACION1 { get; set; }
    }
}
