//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE_SWIFT_MT202
    {
        public int num_rep { get; set; }
        public int num_rep_202 { get; set; }
        public int tipo_202 { get; set; }
        public int agencia { get; set; }
        public System.DateTime fecha_reporte { get; set; }
        public byte status_reporte { get; set; }
        public bool definitivo { get; set; }
        public bool reimpresion { get; set; }
        public string basic_header { get; set; }
        public string app_header { get; set; }
        public string campo_20 { get; set; }
        public string campo_21 { get; set; }
        public string campo_32 { get; set; }
        public string campo_52 { get; set; }
        public string campo_53_D { get; set; }
        public string campo_53_1 { get; set; }
        public string campo_57_A { get; set; }
        public string campo_57_1 { get; set; }
        public string campo_58_A { get; set; }
        public string campo_58_1 { get; set; }
        public string campo_72_1 { get; set; }
        public bool dep_mayor { get; set; }
        public bool ret_mayor { get; set; }
    }
}
