//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETIRO_PME
    {
        public int operacion { get; set; }
        public string causa { get; set; }
        public string centro_regional { get; set; }
        public string nombre_centro_regional { get; set; }
        public string plaza { get; set; }
        public string nombre_plaza { get; set; }
        public string sucursal { get; set; }
        public string nombre_sucursal { get; set; }
        public Nullable<int> cr_patrimonial { get; set; }
        public Nullable<int> referencia { get; set; }
        public Nullable<decimal> numero_cheque { get; set; }
        public Nullable<byte> tipo_documento { get; set; }
        public Nullable<byte> tipo_moneda { get; set; }
        public string otro_documento { get; set; }
        public Nullable<int> referencia_ced { get; set; }
    
        public virtual OPERACION OPERACION1 { get; set; }
        public virtual TIPO_DOCUMENTO TIPO_DOCUMENTO1 { get; set; }
    }
}
