//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALDOS_KAPITI
    {
        public string agencia { get; set; }
        public string cuenta_cliente { get; set; }
        public string sufijo { get; set; }
        public decimal saldo { get; set; }
        public decimal interes { get; set; }
        public string cuenta_bloqueada { get; set; }
        public System.DateTime fecha_generacion { get; set; }
        public int numero_registros { get; set; }
        public string fin_registro { get; set; }
    }
}
