//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALDOS_CD_KAPITI_1
    {
        public string deal_reference { get; set; }
        public string agencia { get; set; }
        public string cuenta_cliente { get; set; }
        public string sufijo { get; set; }
        public string saldo { get; set; }
        public string fecha_generacion { get; set; }
        public string numero_registros { get; set; }
        public string intereses { get; set; }
        public string fin_registro { get; set; }
    }
}
