//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TICKETEntities : DbContext
    {
        public TICKETEntities()
            : base("name=TICKETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PARAMETRIZACION> PARAMETRIZACION { get; set; }
        public virtual DbSet<BITACORA_ENVIO_SWIFT_MT202> BITACORA_ENVIO_SWIFT_MT202 { get; set; }
        public virtual DbSet<REPORTE_SWIFT_MT202> REPORTE_SWIFT_MT202 { get; set; }
    
        public virtual int sp_i_InfoMT202(string fechaoperacion1, Nullable<int> agencia1, Nullable<int> agencia3)
        {
            var fechaoperacion1Parameter = fechaoperacion1 != null ?
                new ObjectParameter("fechaoperacion1", fechaoperacion1) :
                new ObjectParameter("fechaoperacion1", typeof(string));
    
            var agencia1Parameter = agencia1.HasValue ?
                new ObjectParameter("agencia1", agencia1) :
                new ObjectParameter("agencia1", typeof(int));
    
            var agencia3Parameter = agencia3.HasValue ?
                new ObjectParameter("agencia3", agencia3) :
                new ObjectParameter("agencia3", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_i_InfoMT202", fechaoperacion1Parameter, agencia1Parameter, agencia3Parameter);
        }
    }
}
