//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DOCUMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_DOCUMENTO()
        {
            this.DEPOSITO = new HashSet<DEPOSITO>();
            this.RETIRO_PME = new HashSet<RETIRO_PME>();
        }
    
        public byte tipo_documento1 { get; set; }
        public string descripcion_documento { get; set; }
        public short operacion_definida_global { get; set; }
        public bool necesita_especificacion { get; set; }
        public bool status_folio { get; set; }
        public System.DateTime hora_inicio { get; set; }
        public System.DateTime hora_fin { get; set; }
        public string tran_code { get; set; }
        public bool otras_divisas { get; set; }
        public bool detalle_instrumento { get; set; }
        public Nullable<byte> orden { get; set; }
        public string titulo1 { get; set; }
        public string titulo2 { get; set; }
        public bool activo { get; set; }
        public string descripcion_detalle { get; set; }
        public Nullable<System.DateTime> hora_ini_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPOSITO> DEPOSITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETIRO_PME> RETIRO_PME { get; set; }
    }
}
