//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_REPORTE_SWIFT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_REPORTE_SWIFT()
        {
            this.REPORTE_SWIFT = new HashSet<REPORTE_SWIFT>();
        }
    
        public byte tipo_reporte_swift1 { get; set; }
        public byte agencia { get; set; }
        public string desc_tipo_reporte_swift { get; set; }
        public string clave_swift { get; set; }
        public short operacion_definida_global { get; set; }
        public string descripcion_swift { get; set; }
        public string mnemonico_swift { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORTE_SWIFT> REPORTE_SWIFT { get; set; }
    }
}
