//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIDAD_ORGANIZACIONAL
    {
        public int unidad_organizacional1 { get; set; }
        public string unidad_org_bancomer { get; set; }
        public Nullable<byte> tipo_unidad_organizacional { get; set; }
        public string descripcion_unidad_organizacio { get; set; }
        public int unidad_organizacional_padre { get; set; }
        public byte estrategica { get; set; }
    }
}
