//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_X_APLICACION
    {
        public short usuario { get; set; }
        public short aplicacion { get; set; }
        public System.DateTime fecha_login { get; set; }
        public string equipo { get; set; }
    
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
